# Generated by Django 3.1.5 on 2021-07-11 07:10

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ideapeacher', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ideapeacher',
            new_name='MyUser',
        ),
    ]
