# Generated by Django 3.1.5 on 2021-07-11 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ideapeacher', '0002_auto_20210711_1240'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='idprove',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='myuser',
            name='mobile',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
