# Generated by Django 3.1.5 on 2021-07-11 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ideapeacher', '0003_auto_20210711_1312'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='idproveno',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
