# Generated by Django 3.1.5 on 2021-07-14 21:50

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ideapeacher', '0004_myuser_idproveno'),
    ]

    operations = [
        migrations.CreateModel(
            name='category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='idea',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Post_idea', models.TextField()),
                ('date_created', models.DateTimeField(default=datetime.datetime(2021, 7, 15, 3, 20, 27, 524038))),
                ('pdf', models.FileField(blank=True, upload_to='book/pdfs')),
                ('category', models.ManyToManyField(to='ideapeacher.category')),
                ('peacher', models.ForeignKey(default=False, on_delete=django.db.models.deletion.CASCADE, to='ideapeacher.myuser')),
            ],
        ),
    ]
