# Generated by Django 3.1.5 on 2021-07-15 14:58

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ideapeacher', '0006_auto_20210715_0324'),
    ]

    operations = [
        migrations.AlterField(
            model_name='idea',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2021, 7, 15, 20, 28, 12, 614941)),
        ),
        migrations.CreateModel(
            name='Public',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField()),
                ('date_created', models.DateTimeField(default=datetime.datetime(2021, 7, 15, 20, 28, 12, 614941))),
                ('byUser', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('on_post', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='ideapeacher.idea')),
            ],
        ),
    ]
