# Generated by Django 3.1.5 on 2021-07-15 15:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ideapeacher', '0007_auto_20210715_2028'),
    ]

    operations = [
        migrations.AlterField(
            model_name='idea',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2021, 7, 15, 20, 46, 59, 73242)),
        ),
        migrations.AlterField(
            model_name='public',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2021, 7, 15, 20, 46, 59, 73242)),
        ),
    ]
